/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* top =  1  *)
(* src = "tests/add2.v:1.1-14.10" *)
module add2(a_0, a_1, b_0, b_1, c_0, c_1);
  (* src = "tests/add2.v:2.9-2.12" *)
  input a_0;
  wire a_0;
  (* src = "tests/add2.v:3.9-3.12" *)
  input a_1;
  wire a_1;
  (* src = "tests/add2.v:4.9-4.12" *)
  input b_0;
  wire b_0;
  (* src = "tests/add2.v:5.9-5.12" *)
  input b_1;
  wire b_1;
  (* src = "tests/add2.v:6.10-6.13" *)
  output c_0;
  wire c_0;
  (* src = "tests/add2.v:7.10-7.13" *)
  output c_1;
  wire c_1;
  assign { c_1, c_0 } = { a_1, a_0 } + (* src = "tests/add2.v:11.16-11.39" *) { b_1, b_0 };
endmodule
