/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* src = "tests/sync_reset_n.v:1.1-19.10" *)
module sync_reset(clock, reset_n, d, q);
  (* src = "tests/sync_reset_n.v:2.9-2.14" *)
  input clock;
  wire clock;
  (* src = "tests/sync_reset_n.v:4.9-4.10" *)
  input d;
  wire d;
  (* src = "tests/sync_reset_n.v:5.10-5.11" *)
  output q;
  wire q;
  (* src = "tests/sync_reset_n.v:7.7-7.12" *)
  reg q_reg;
  (* src = "tests/sync_reset_n.v:3.9-3.16" *)
  input reset_n;
  wire reset_n;
  (* src = "tests/sync_reset_n.v:9.3-15.6" *)
  always @(posedge clock)
    if (!reset_n) q_reg <= 1'h0;
    else q_reg <= d;
  assign q = q_reg;
endmodule
