site_name: 数字逻辑设计实验文档
site_description: 'Documentation for labs of Digital Logic Design course'
site_author: 'Digital Logic Design Course Team'
site_url: https://lab.cs.tsinghua.edu.cn/digital-design/doc/
copyright: 'Copyright &copy; 2020-2023 Department of Computer Science and Technology, Tsinghua University. All Rights Reserved.'

theme: 
  name: 'material'
  language: 'zh'
  custom_dir: 'theme-override/'
  icon:
    logo: material/developer-board
    repo: fontawesome/brands/github
  features:
    - navigation.instant
    - content.tabs.link


repo_name: 'thu-cs-lab/Digital-Design-Docs'
repo_url: 'https://github.com/thu-cs-lab/Digital-Design-Docs'

nav:
  - 数字逻辑设计实验:
    - 总述: index.md
    - 项目设计: project.md
    - HDL 编程:
      - 时钟相关: hdl/clocking.md
      - 复位相关: hdl/reset.md
      - 总线协议: hdl/bus.md
      - 调试相关: hdl/debug.md
      - 三态门: hdl/tri.md
    - 硬件相关:
      - 实验板: hardware/board.md
      - 板载外设: hardware/onboard.md
      - 外接外设: hardware/peripheral.md
    - Quartus 使用: quartus.md
    - 常用软件: software.md
    - 常见问题: faq.md
  - 通过例子学硬件描述语言:
    - 总述: hdl-by-example/overview.md
    - 加法器: hdl-by-example/adder.md
    - 按钮开关: hdl-by-example/button.md
    - 秒表: hdl-by-example/timer.md
    - 计数器: hdl-by-example/counter.md
    - 无状态仲裁器: hdl-by-example/priority_encoder.md
    - 循环优先级仲裁器: hdl-by-example/rr_arbiter.md
    - 代码规范: hdl-by-example/coding_standard.md
    - 仿真: hdl-by-example/simulation.md

extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - git-revision-date-localized:
      fallback_to_build_date: true
      locale: zh
  - git-authors:
      show_contribution: true
      show_line_count: true
      count_empty_lines: true
      fallback_to_empty: false
  - wavedrom:
      embed_svg: true
      pymdownx: true

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
      linenums: true
  - footnotes
  - def_list
  - meta
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: wavedrom
          class: wavedrom
          format: !!python/name:markdownwavedrom.plugin.fence_wavedrom_format
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

extra:
  pagetime: 'on'
  analytics:
    provider: google
    property: G-69YPS2LP7R
  xapi:
    ident: digital-logic-design
    auth: 'XAPI_TOKEN'
    endpoint: 'XAPI_URL'
