/* Generated by Yosys 0.16+6 (git sha1 e0ba32423, clang 11.0.1-2 -fPIC -Os) */

module add2(a, b, c);
  wire _0_;
  wire _1_;
  input [1:0] a;
  wire [1:0] a;
  input [1:0] b;
  wire [1:0] b;
  output [1:0] c;
  wire [1:0] c;
  assign _0_ = b[0] & a[0];
  assign _1_ = b[1] ^ a[1];
  assign c[1] = _0_ ^ _1_;
  assign c[0] = b[0] ^ a[0];
endmodule
