/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* src = "examples/adder.v:1.1-7.10" *)
module add2(a, b, c);
  wire _0_;
  wire _1_;
  (* src = "examples/adder.v:2.15-2.16" *)
  input [1:0] a;
  wire [1:0] a;
  (* src = "examples/adder.v:3.15-3.16" *)
  input [1:0] b;
  wire [1:0] b;
  (* src = "examples/adder.v:4.16-4.17" *)
  output [1:0] c;
  wire [1:0] c;
  assign _0_ = b[0] & a[0];
  assign _1_ = b[1] ^ a[1];
  assign c[1] = _0_ ^ _1_;
  assign c[0] = b[0] ^ a[0];
endmodule
