/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* src = "examples/button.sv:1.1-13.10" *)
module button(button, light);
  (* src = "examples/button.sv:7.3-9.6" *)
  wire _0_;
  (* src = "examples/button.sv:2.9-2.15" *)
  input button;
  wire button;
  (* src = "examples/button.sv:3.10-3.15" *)
  output light;
  wire light;
  (* src = "examples/button.sv:5.7-5.16" *)
  reg light_reg;
  assign _0_ = ~light_reg;
  (* \always_ff  = 32'd1 *)
  (* src = "examples/button.sv:7.3-9.6" *)
  always @(posedge button)
    light_reg <= _0_;
  assign light = light_reg;
endmodule
