/* Generated by Yosys 0.16+6 (git sha1 e0ba32423, clang 11.0.1-2 -fPIC -Os) */

module button(button, light);
  wire _0_;
  input button;
  wire button;
  output light;
  wire light;
  reg light_reg;
  assign _0_ = ~light_reg;
  always @(posedge button)
    light_reg <= _0_;
  assign light = light_reg;
endmodule
