/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* src = "examples/counter.v:34.1-68.10" *)
module counter(clock, reset, button_debounced, ones, tens);
  wire _00_;
  (* src = "examples/counter.v:54.11-54.52" *)
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* force_downto = 32'd1 *)
  (* src = "examples/counter.v:57.23-57.38|/home/jiegec/prefix/yosys/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [3:0] _19_;
  (* force_downto = 32'd1 *)
  (* src = "examples/counter.v:57.23-57.38|/home/jiegec/prefix/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [3:0] _20_;
  (* src = "examples/counter.v:37.9-37.25" *)
  input button_debounced;
  wire button_debounced;
  (* src = "examples/counter.v:44.7-44.27" *)
  reg button_debounced_reg;
  (* src = "examples/counter.v:35.9-35.14" *)
  input clock;
  wire clock;
  (* src = "examples/counter.v:38.16-38.20" *)
  output [3:0] ones;
  wire [3:0] ones;
  (* src = "examples/counter.v:42.13-42.21" *)
  reg [3:0] ones_reg;
  (* src = "examples/counter.v:36.9-36.14" *)
  input reset;
  wire reset;
  (* src = "examples/counter.v:39.16-39.20" *)
  output [3:0] tens;
  wire [3:0] tens;
  (* src = "examples/counter.v:43.13-43.21" *)
  reg [3:0] tens_reg;
  assign _19_[0] = ~tens_reg[0];
  assign _06_ = ~button_debounced_reg;
  assign _02_ = ~ones_reg[0];
  assign _07_ = ~ones_reg[2];
  assign _01_ = button_debounced & _06_;
  assign _08_ = _07_ & ones_reg[3];
  assign _09_ = ~(_07_ & ones_reg[3]);
  assign _10_ = ~(_02_ | ones_reg[1]);
  assign _11_ = _08_ & _10_;
  assign _00_ = _01_ & _11_;
  assign _12_ = ones_reg[0] & ones_reg[1];
  assign _13_ = ~(_02_ & ones_reg[1]);
  assign _14_ = ~(_09_ & _10_);
  assign _03_ = ~(_13_ & _14_);
  assign _15_ = ~(ones_reg[2] & _12_);
  assign _04_ = ones_reg[2] ^ _12_;
  assign _16_ = ones_reg[3] ^ _15_;
  assign _05_ = ~(_11_ | _16_);
  assign _17_ = tens_reg[0] & tens_reg[1];
  assign _20_[1] = tens_reg[0] ^ tens_reg[1];
  assign _18_ = tens_reg[2] & _17_;
  assign _20_[2] = tens_reg[2] ^ _17_;
  assign _20_[3] = tens_reg[3] ^ _18_;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) button_debounced_reg <= 1'h0;
    else button_debounced_reg <= button_debounced;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) ones_reg[0] <= 1'h0;
    else if (_01_) ones_reg[0] <= _02_;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) ones_reg[1] <= 1'h0;
    else if (_01_) ones_reg[1] <= _03_;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) ones_reg[2] <= 1'h0;
    else if (_01_) ones_reg[2] <= _04_;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) ones_reg[3] <= 1'h0;
    else if (_01_) ones_reg[3] <= _05_;
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) tens_reg[0] <= 1'h0;
    else if (_00_) tens_reg[0] <= _19_[0];
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) tens_reg[1] <= 1'h0;
    else if (_00_) tens_reg[1] <= _20_[1];
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) tens_reg[2] <= 1'h0;
    else if (_00_) tens_reg[2] <= _20_[2];
  (* src = "examples/counter.v:46.3-63.6" *)
  always @(posedge clock)
    if (reset) tens_reg[3] <= 1'h0;
    else if (_00_) tens_reg[3] <= _20_[3];
  assign _19_[3:1] = tens_reg[3:1];
  assign _20_[0] = _19_[0];
  assign ones = ones_reg;
  assign tens = tens_reg;
endmodule

(* src = "examples/counter.v:70.1-95.10" *)
module counter_top(clock, reset, button, ones, tens);
  (* src = "examples/counter.v:73.9-73.15" *)
  input button;
  wire button;
  (* src = "examples/counter.v:78.8-78.24" *)
  wire button_debounced;
  (* src = "examples/counter.v:71.9-71.14" *)
  input clock;
  wire clock;
  (* src = "examples/counter.v:74.16-74.20" *)
  output [3:0] ones;
  wire [3:0] ones;
  (* src = "examples/counter.v:72.9-72.14" *)
  input reset;
  wire reset;
  (* src = "examples/counter.v:75.16-75.20" *)
  output [3:0] tens;
  wire [3:0] tens;
  (* module_not_derived = 32'd1 *)
  (* src = "examples/counter.v:87.11-93.4" *)
  counter counter_component (
    .button_debounced(button_debounced),
    .clock(clock),
    .ones(ones),
    .reset(reset),
    .tens(tens)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "examples/counter.v:80.13-85.4" *)
  debouncer debouncer_component (
    .button(button),
    .button_debounced(button_debounced),
    .clock(clock),
    .reset(reset)
  );
endmodule

(* src = "examples/counter.v:1.1-32.10" *)
module debouncer(clock, reset, button, button_debounced);
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  (* force_downto = 32'd1 *)
  (* src = "examples/counter.v:23.26-23.45|/home/jiegec/prefix/yosys/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [15:0] _035_;
  (* force_downto = 32'd1 *)
  (* src = "examples/counter.v:23.26-23.45|/home/jiegec/prefix/yosys/bin/../share/yosys/techmap.v:270.26-270.27" *)
  wire [15:0] _036_;
  (* src = "examples/counter.v:4.9-4.15" *)
  input button;
  wire button;
  (* src = "examples/counter.v:5.10-5.26" *)
  output button_debounced;
  wire button_debounced;
  (* src = "examples/counter.v:9.7-9.27" *)
  reg button_debounced_reg;
  (* src = "examples/counter.v:2.9-2.14" *)
  input clock;
  wire clock;
  (* src = "examples/counter.v:8.14-8.25" *)
  reg [15:0] counter_reg;
  (* src = "examples/counter.v:7.7-7.22" *)
  reg last_button_reg;
  (* src = "examples/counter.v:3.9-3.14" *)
  input reset;
  wire reset;
  assign _035_[0] = ~counter_reg[0];
  assign _003_ = ~counter_reg[5];
  assign _004_ = ~counter_reg[11];
  assign _005_ = ~counter_reg[12];
  assign _006_ = _003_ & counter_reg[4];
  assign _007_ = ~(counter_reg[7] | counter_reg[6]);
  assign _008_ = _006_ & _007_;
  assign _009_ = ~(counter_reg[1] | counter_reg[0]);
  assign _010_ = ~(counter_reg[3] | counter_reg[2]);
  assign _011_ = _009_ & _010_;
  assign _012_ = _008_ & _011_;
  assign _013_ = _005_ & counter_reg[13];
  assign _014_ = ~(counter_reg[15] | counter_reg[14]);
  assign _015_ = _013_ & _014_;
  assign _016_ = counter_reg[9] & counter_reg[8];
  assign _017_ = _004_ & counter_reg[10];
  assign _018_ = _016_ & _017_;
  assign _019_ = _015_ & _018_;
  assign _002_ = ~(_012_ & _019_);
  assign _020_ = last_button_reg ^ button;
  assign _001_ = reset | _020_;
  assign _000_ = ~(_002_ | _020_);
  assign _021_ = counter_reg[1] & counter_reg[0];
  assign _036_[1] = ~(_009_ | _021_);
  assign _022_ = counter_reg[2] & _021_;
  assign _036_[2] = counter_reg[2] ^ _021_;
  assign _023_ = counter_reg[3] & _022_;
  assign _036_[3] = counter_reg[3] ^ _022_;
  assign _024_ = counter_reg[4] & _023_;
  assign _036_[4] = counter_reg[4] ^ _023_;
  assign _025_ = counter_reg[5] & _024_;
  assign _036_[5] = counter_reg[5] ^ _024_;
  assign _026_ = counter_reg[6] & _025_;
  assign _036_[6] = counter_reg[6] ^ _025_;
  assign _027_ = counter_reg[7] & _026_;
  assign _036_[7] = counter_reg[7] ^ _026_;
  assign _028_ = counter_reg[8] & _027_;
  assign _036_[8] = counter_reg[8] ^ _027_;
  assign _029_ = counter_reg[9] & _028_;
  assign _036_[9] = counter_reg[9] ^ _028_;
  assign _030_ = counter_reg[10] & _029_;
  assign _036_[10] = counter_reg[10] ^ _029_;
  assign _031_ = counter_reg[11] & _030_;
  assign _036_[11] = counter_reg[11] ^ _030_;
  assign _032_ = counter_reg[12] & _031_;
  assign _036_[12] = counter_reg[12] ^ _031_;
  assign _033_ = counter_reg[13] & _032_;
  assign _036_[13] = counter_reg[13] ^ _032_;
  assign _034_ = counter_reg[14] & _033_;
  assign _036_[14] = counter_reg[14] ^ _033_;
  assign _036_[15] = counter_reg[15] ^ _034_;
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (reset) last_button_reg <= 1'h0;
    else last_button_reg <= button;
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[0] <= 1'h0;
    else if (_002_) counter_reg[0] <= _035_[0];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[1] <= 1'h0;
    else if (_002_) counter_reg[1] <= _036_[1];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[2] <= 1'h0;
    else if (_002_) counter_reg[2] <= _036_[2];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[3] <= 1'h0;
    else if (_002_) counter_reg[3] <= _036_[3];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[4] <= 1'h0;
    else if (_002_) counter_reg[4] <= _036_[4];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[5] <= 1'h0;
    else if (_002_) counter_reg[5] <= _036_[5];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[6] <= 1'h0;
    else if (_002_) counter_reg[6] <= _036_[6];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[7] <= 1'h0;
    else if (_002_) counter_reg[7] <= _036_[7];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[8] <= 1'h0;
    else if (_002_) counter_reg[8] <= _036_[8];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[9] <= 1'h0;
    else if (_002_) counter_reg[9] <= _036_[9];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[10] <= 1'h0;
    else if (_002_) counter_reg[10] <= _036_[10];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[11] <= 1'h0;
    else if (_002_) counter_reg[11] <= _036_[11];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[12] <= 1'h0;
    else if (_002_) counter_reg[12] <= _036_[12];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[13] <= 1'h0;
    else if (_002_) counter_reg[13] <= _036_[13];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[14] <= 1'h0;
    else if (_002_) counter_reg[14] <= _036_[14];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (_001_) counter_reg[15] <= 1'h0;
    else if (_002_) counter_reg[15] <= _036_[15];
  (* src = "examples/counter.v:11.3-29.6" *)
  always @(posedge clock)
    if (reset) button_debounced_reg <= 1'h0;
    else if (_000_) button_debounced_reg <= last_button_reg;
  assign _035_[15:1] = counter_reg[15:1];
  assign _036_[0] = _035_[0];
  assign button_debounced = button_debounced_reg;
endmodule
