/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* top =  1  *)
(* src = "examples/priority_encoder.v:1.1-38.10" *)
module priority_encoder(request, valid, user);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  (* src = "examples/priority_encoder.v:2.15-2.22" *)
  wire _15_;
  (* src = "examples/priority_encoder.v:2.15-2.22" *)
  wire _16_;
  (* src = "examples/priority_encoder.v:2.15-2.22" *)
  wire _17_;
  (* src = "examples/priority_encoder.v:2.15-2.22" *)
  wire _18_;
  (* src = "examples/priority_encoder.v:4.16-4.20" *)
  wire _19_;
  (* src = "examples/priority_encoder.v:4.16-4.20" *)
  wire _20_;
  (* src = "examples/priority_encoder.v:3.10-3.15" *)
  wire _21_;
  (* src = "examples/priority_encoder.v:2.15-2.22" *)
  input [3:0] request;
  wire [3:0] request;
  (* src = "examples/priority_encoder.v:4.16-4.20" *)
  output [1:0] user;
  wire [1:0] user;
  (* src = "examples/priority_encoder.v:7.13-7.22" *)
  wire [1:0] user_comb;
  (* src = "examples/priority_encoder.v:3.10-3.15" *)
  output valid;
  wire valid;
  (* src = "examples/priority_encoder.v:6.7-6.17" *)
  wire valid_comb;
  assign _13_ = ~_17_;
  assign _14_ = ~(_15_ | _16_);
  assign _09_ = ~(_17_ | _18_);
  assign _10_ = _17_ | _18_;
  assign _21_ = ~(_14_ & _09_);
  assign _11_ = _13_ & _18_;
  assign _12_ = ~(_16_ | _11_);
  assign _19_ = ~(_15_ | _12_);
  assign _20_ = _14_ & _10_;
  assign user_comb = user;
  assign valid_comb = valid;
  assign _15_ = request[0];
  assign _16_ = request[1];
  assign _17_ = request[2];
  assign _18_ = request[3];
  assign valid = _21_;
  assign user[0] = _19_;
  assign user[1] = _20_;
endmodule
