/* Generated by Yosys 0.16+41 (git sha1 29c0a5958, clang 11.0.1-2 -fPIC -Os) */

(* top =  1  *)
(* src = "examples/timer.v:1.1-28.10" *)
module timer(clock, reset, timer);
  (* src = "examples/timer.v:11.3-23.6" *)
  wire [19:0] _00_;
  (* src = "examples/timer.v:11.3-23.6" *)
  wire [3:0] _01_;
  (* src = "examples/timer.v:17.22-17.38" *)
  wire [3:0] _02_;
  (* src = "examples/timer.v:20.24-20.43" *)
  wire [19:0] _03_;
  (* src = "examples/timer.v:16.11-16.36" *)
  wire _04_;
  wire [3:0] _05_;
  wire [19:0] _06_;
  (* src = "examples/timer.v:2.9-2.14" *)
  input clock;
  wire clock;
  (* src = "examples/timer.v:8.14-8.25" *)
  reg [19:0] counter_reg;
  (* src = "examples/timer.v:3.9-3.14" *)
  input reset;
  wire reset;
  (* src = "examples/timer.v:4.16-4.21" *)
  output [3:0] timer;
  wire [3:0] timer;
  (* src = "examples/timer.v:7.13-7.22" *)
  reg [3:0] timer_reg;
  assign _02_ = timer_reg + (* src = "examples/timer.v:17.22-17.38" *) 1'h1;
  assign _03_ = counter_reg + (* src = "examples/timer.v:20.24-20.43" *) 1'h1;
  assign _04_ = counter_reg == (* src = "examples/timer.v:16.11-16.36" *) 20'hf423f;
  (* src = "examples/timer.v:11.3-23.6" *)
  always @(posedge clock)
    timer_reg <= _01_;
  (* src = "examples/timer.v:11.3-23.6" *)
  always @(posedge clock)
    counter_reg <= _00_;
  assign _05_ = _04_ ? (* full_case = 32'd1 *) (* src = "examples/timer.v:16.11-16.36|examples/timer.v:16.7-21.10" *) _02_ : timer_reg;
  assign _01_ = reset ? (* full_case = 32'd1 *) (* src = "examples/timer.v:12.9-12.14|examples/timer.v:12.5-22.8" *) 4'h0 : _05_;
  assign _06_ = _04_ ? (* full_case = 32'd1 *) (* src = "examples/timer.v:16.11-16.36|examples/timer.v:16.7-21.10" *) 20'h00000 : _03_;
  assign _00_ = reset ? (* full_case = 32'd1 *) (* src = "examples/timer.v:12.9-12.14|examples/timer.v:12.5-22.8" *) 20'h00000 : _06_;
  assign timer = timer_reg;
endmodule
